
name: 'Common test suite'

# does that work ?
# https://github.com/orgs/community/discussions/18597
defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
      - run: ci/00-prepare-docker.sh
      - run: ci/01-conf.sh
      - run: ci/02-build.sh
      - run: ci/03-check.sh
