
name: 'Common test suite'

# does that work ?
# https://github.com/orgs/community/discussions/18597
# alas, no.
# defaults:
#   run:
#     shell: bash

inputs:
  path:
    description: 'path where the tree was checked out, relative to the runner work directory'
    type: string
    default: .

runs:
  using: "composite"
  steps:
      - run: ci/00-prepare-docker.sh
        working-directory: ${{ inputs.path }}
        shell: sh
      - run: ci/01-conf.sh
        working-directory: ${{ inputs.path }}
        shell: bash
      - run: ci/02-build.sh
        working-directory: ${{ inputs.path }}
        shell: bash
      - run: ci/03-check.sh
        working-directory: ${{ inputs.path }}
        shell: bash
