if(HAVE_AVX512VL)
    message(STATUS "Testing if bug 30027 (gcc bug 89229) is present")
    try_compile(bug30027_compiles ${PROJECT_BINARY_DIR}/config
        ${PROJECT_SOURCE_DIR}/config/bug30027.cpp)
    if(bug30027_compiles)
        message(STATUS "Testing if bug 30027 (gcc bug 89229) is present -- No")
    else()
        message(STATUS "Testing if bug 30027 (gcc bug 89229) is present -- Yes, disabling avx512vl. Use a newer compiler to fix. See https://gitlab.inria.fr/cado-nfs/cado-nfs/-/issues/30027")
        string(REPLACE "-mavx512vl" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
        string(REPLACE "-mavx512vl" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
        set (HAVE_AVX512VL 0)
    endif()
endif()
