#
# This Dockerfile is an example. It calls the same preparation script as
# our CI jobs, and embeds some bonus software for debugging.
# Most probably, you'll want to edit it, and start from other images,
# and/or add a few packages as well.

FROM debian:unstable
ENV DOCKER_SCRIPT=1
COPY 0??-*.sh ??-*.sh /tmp/
RUN /tmp/00-prepare-docker.sh

# vim: filetype=dockerfile:
