name: 32-bit checks
on: [push]

jobs:
  checks:
    strategy:
      matrix:
        instance: [
          'on debian system with 32-bit gcc',
          'on debian-testing system with 32-bit gcc',
        ]
    # because this is a reusable workflow, we don't need a checkout to
    # call this.
    uses: ./.github/workflows/prepare-and-use-container.yml
    with:
      job-name: 'checks ${{ matrix.instance }}'
      registry: registry.gitlab.inria.fr
    secrets:
      username: ${{ secrets.INRIA_GITLAB_REGISTRY_USERNAME }}
      password: ${{ secrets.INRIA_GITLAB_REGISTRY_PASSWORD }}
