name: main checks
on: [push]

jobs:
  checks:
    strategy:
      # because github is able to fail-fast, there's no pressing need to
      # defer the launch of the few expensive checks.
      matrix:
        # we have two gcc:latest (one for normal checks, one for
        # expensive checks, and three debian-testing (one normal, one
        # with 32-bit abi, and one with shared libs). It could make sense
        # to share a few of them a little bit.
        instance: [
          'with gcc',
          'on alpine system with gcc',
          'on debian system with 32-bit gcc',
          'on ubuntu system with gcc',
          'on ubuntu rolling system with gcc',
          'on debian-testing system with 32-bit gcc',
          'using cmake directly with gcc',
          'on debian system with gcc',
          'on debian-testing system with gcc',
          'shared libs on debian-testing system with gcc',
          'on debian10 system with gcc',
          'on debian9 system with gcc',
          'on opensuse system with gcc',
          'on fedora system with gcc',
          'on centos system with gcc',
          'on centos9 system with gcc',
          'with clang13',
          'with clangdev',
          'with icc',
          'expensive with gcc',
        ]
    # because this is a reusable workflow, we don't need a checkout to
    # call this.
    uses: ./.github/workflows/prepare-and-use-container.yml
    with:
      job-name: 'checks ${{ matrix.instance }}'
      # registry: ghcr.io
      registry: registry.gitlab.inria.fr
      username: ${{ secrets.INRIA_GITLAB_REGISTRY_USERNAME }}
      password: ${{ secrets.INRIA_GITLAB_REGISTRY_PASSWORD }}

