
name: early
# The name goes to $GITHUB_WORKFLOW

run-name: early builds
on: [push]

jobs:
  checks-with-gcc:
    runs-on: [self-hosted, linux, x64]
    container: gcc:latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-suite
