name: main
on: [push]

jobs:
  checks:
    strategy:
      # because github is able to fail-fast, there's no pressing need to
      # defer the launch of the few expensive checks.
      matrix:
        # we have two gcc:latest (one for normal checks, one for
        # expensive checks, and three debian-testing (one normal, one
        # with 32-bit abi, and one with shared libs). It could make sense
        # to share a few of them a little bit.
        instance: [
          'on alpine system with gcc',
          'on ubuntu system with gcc',
          'on ubuntu rolling system with gcc',
          'on debian system with gcc',
          'on debian-testing system with gcc',
          'on debian10 system with gcc',
          'on debian9 system with gcc',
          'on opensuse system with gcc',
          'on fedora system with gcc',
          'on centos system with gcc',
          'on centos9 system with gcc',
        ]
    # because this is a reusable workflow, we don't need a checkout to
    # call this.
    uses: ./.github/workflows/prepare-and-use-container.yml
    with:
      job-name: 'checks ${{ matrix.instance }}'
    #   registry: ghcr.io
    # secrets:
    #   username: ${{ github.actor }}
    #   password: ${{ secrets.GITHUB_TOKEN }}
      registry: registry.gitlab.inria.fr
    secrets:
      username: ${{ secrets.INRIA_GITLAB_REGISTRY_USERNAME }}
      password: ${{ secrets.INRIA_GITLAB_REGISTRY_PASSWORD }}

  checks-compilers:
    strategy:
      matrix:
        instance: [ 'gcc', 'clang13', 'clangdev', 'icc', ]
    uses: ./.github/workflows/prepare-and-use-container.yml
    with:
      job-name: 'checks with ${{ matrix.instance }}'
    #   registry: ghcr.io
    # secrets:
    #   username: ${{ github.actor }}
    #   password: ${{ secrets.GITHUB_TOKEN }}
      registry: registry.gitlab.inria.fr
    secrets:
      username: ${{ secrets.INRIA_GITLAB_REGISTRY_USERNAME }}
      password: ${{ secrets.INRIA_GITLAB_REGISTRY_PASSWORD }}

  checks-features:
    strategy:
      matrix:
        instance: [
          'using cmake directly with gcc',
          'shared libs on debian-testing system with gcc',
        ]
    uses: ./.github/workflows/prepare-and-use-container.yml
    with:
      job-name: 'checks ${{ matrix.instance }}'
    #   registry: ghcr.io
    # secrets:
    #   username: ${{ github.actor }}
    #   password: ${{ secrets.GITHUB_TOKEN }}
      registry: registry.gitlab.inria.fr
    secrets:
      username: ${{ secrets.INRIA_GITLAB_REGISTRY_USERNAME }}
      password: ${{ secrets.INRIA_GITLAB_REGISTRY_PASSWORD }}

  checks-32-bit:
    strategy:
      matrix:
        instance: [
          'on debian system with 32-bit gcc',
          'on debian-testing system with 32-bit gcc',
        ]
    uses: ./.github/workflows/prepare-and-use-container.yml
    with:
      job-name: 'checks ${{ matrix.instance }}'
    #   registry: ghcr.io
    # secrets:
    #   username: ${{ github.actor }}
    #   password: ${{ secrets.GITHUB_TOKEN }}
      registry: registry.gitlab.inria.fr
    secrets:
      username: ${{ secrets.INRIA_GITLAB_REGISTRY_USERNAME }}
      password: ${{ secrets.INRIA_GITLAB_REGISTRY_PASSWORD }}

  long-checks:
    strategy:
      matrix:
        instance: [
          'expensive with gcc',
        ]
    uses: ./.github/workflows/prepare-and-use-container.yml
    with:
      job-name: 'checks ${{ matrix.instance }}'
    #   registry: ghcr.io
    # secrets:
    #   username: ${{ github.actor }}
    #   password: ${{ secrets.GITHUB_TOKEN }}
      registry: registry.gitlab.inria.fr
    secrets:
      username: ${{ secrets.INRIA_GITLAB_REGISTRY_USERNAME }}
      password: ${{ secrets.INRIA_GITLAB_REGISTRY_PASSWORD }}
